#define APP_USE_LTE false
#define APP_USE_WIFI true
#define DEBUG_COLOR 1

#define USE_OLED 1
#define OLED_GEOMETRY GEOMETRY_128_32
#define OLED_LINE_ACTION 0
#define OLED_LINE_STATUS 1
#define OLED_LINE_ERROR 2

