#BOARD ?= espressif:esp32:esp32
BOARD ?= espressif:esp32:ttgo-t7-v13-mini32
BAUD = 230400
#BOARD_OPTIONS ?= CDCOnBoot=cdc
PARTITION_SCHEME ?= min_spiffs


include ../../cli.mk
CPPFLAGS:=$(CPPFLAGS) -I../.. -I../common

